replicaCount: 1

image:
  repository: bgeesaman/nginx-test
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: "nginx"
fullnameOverride: "nginx-test"

service:
  type: ClusterIP
  port: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
